# Basic Linear Algebra with Python
Copyright 2020.  Siman Wong

In this document I will show you the basic python syntax for python programming in connection with Math 545.  We will only use a very small subsets of the language.  **Important note:** For Math 545 we will use <font color="red">**Python 3.7 or above**</font>.

There are many online resources and references for python, and I have used some of them as I prepare this and other documents I use today (I will give proper credits later in the semester).  I do hope that I have picked out a minimal and yet very useable subset of python that will faciliate your study and applications of linear algebra.


What makes python so popular, besides being user-friendly, is that it has a *huge* collection of libraries that allow us to complex calculations/programming without first reinventing the wheel.  From now on, **insert the following lines in the first (code) cell of *every* JN notebook for Math 545**:

In [1]:
import numpy as np             # numpy stands for "numerical python"
import matplotlib.pyplot as plt
import scipy.linalg as spla    # scipy: scientific python

# remember that we can execute more than more command on one cell,
# but you will see an output only from the last command

Note that we are not getting any output; that's because we simply load two libraries (and give each one a name so we don't have to type the full name everytime).  Also the "#" symbol signifies that the text following the symbols are comments and will be ignored by python.  

*It is a good habit to add comments to your codes*.

====================================

In the Intro-to-JN slides I aleady showed you show to print stuff:

In [2]:
print("hello world")
print("Pi is not equal to ", 22/7)

# remember that by default, python turns fractions into decimals,
# EVEN IF THE FRACTION IS AN INTEGER:

print("Look what happens when we divide 4 by 2:  ", 4/2)

hello world
Pi is not equal to  3.142857142857143
Look what happens when we divide 4 by 2:   2.0


### Matrices and Vectors

This being a class on linear algebra, the first and foremost objects we are interested in are **matrices** and **vectors**.   But first, a quick python-digression.  It's a bit of CS-inside baseball, but I want to bring it up now to avoid future confusion.

Python has a built-in "list" data structure that resembles a row vector (in the mathematical sense), and the entries of a python "list" can be pretty much anything, includings lists.  This allows us to build data structure that resembles a mathematical matrix.  *However*, for various techincal reasons such structures are **not compatible** with the aforementioned python math libraries.  Instead we need to use numpy's built-in **numpy array** types.

*Up-shot*, especially for those who have experience with Python but not numpy:  <font color="red">**Use numpy arrays exclusive for linear algebra**.</font>

Python's list data structure are very useful in its own right, and we will make reference to it later in *programming contexts*.  Just make sure you don't confuse the two.

In [3]:
# Now, it's time to play with numpy arrays.  It's actually very easy.
# To define a 2x3 matrix

A = np.array([ [7,8,9], [-4,-5,-6] ])

print("A:")
print(A)

A:
[[ 7  8  9]
 [-4 -5 -6]]


### Indexing of entries of python matrices and vectors

In standard math notation, the "(1,2)" entry of the matrix A above is 8.  Try's try that:



In [4]:
A[1,2]

# what's going on?

-6

You can probably tell what happens:  In **Python**, <font color="red">index of arrays and vectors starts at **position 0**.</font>  So again in the example
   
   A = np.array([ [7,8,9], [-4,-5,-6] ])
   
the index of the entry 8 is (0,1)!  Let's try that:

In [5]:
A[0,1]

8

This is a purely notational convention; just keep that in mind (very common source of mistake).

Another common source of mistake: row-vector vs matrices-with-one-row:

In [6]:
# Here is a row vector

B = np.array([ 3, 0.2, 16/7])

# Here is a 1x3 matrix

C = np.array([ [3, 0.2, 16/7] ] )

print("B")
print(B)
print("C")
print(C)

B
[3.         0.2        2.28571429]
C
[[3.         0.2        2.28571429]]


To see the difference between the two, let's try to access say the "first entry":

In [7]:
print(B[0])
print(C[0])

#see the difference?!!

3.0
[3.         0.2        2.28571429]


In [8]:
# We can also verify directly the "shape" of the matrices/arrays
# we just created:

print("np.shape of A:  ", np.shape(A))
print("np.shape of B:  ", np.shape(B))
print("np.shape of C:  ", np.shape(C))

# by the way: Do you notice that I just cleverly introduce to you a
# new python function *np.shape* ?!

np.shape of A:   (2, 3)
np.shape of B:   (3,)
np.shape of C:   (1, 3)


### Practice:  (not to be handed in, but make sure you tried this at home)

Numpy does have a built-in "size" function; run the codes in the next cell and see if you can figure out what they do.

In [9]:
# run these yourself!

print("numpy size of A:  ", np.size(A))
print("numpy size of B:  ", np.size(B))
print("numpy size of C:  ", np.size(C))

numpy size of A:   6
numpy size of B:   3
numpy size of C:   3


Let's continue.  It's easy to pick out specific row's and columnn of a matrix --- keeping in mind that you need to use **python's indexing**:

In [10]:
print("A:  ", A)

row = A[ 1, : ]
print("row with python index 1:  ", row)
print("np.shape of this row:  ", np.shape(row))

col = A[ : , 1]
print("col with python index 1: ", col)
print("np.shape of this col:  ", np.shape(col))


A:   [[ 7  8  9]
 [-4 -5 -6]]
row with python index 1:   [-4 -5 -6]
np.shape of this row:   (3,)
col with python index 1:  [ 8 -5]
np.shape of this col:   (2,)


### Practice:

Look at the output **np.shape** for row vs column above:  why is that a bit surprising, and based on that, what <font color="red">**precaution**</font> do you need to make when you use the **np.shape** to <font color="red">**extract columns"**</font>?  Would you have similar issues if you try to <font color="red">**extract a row"**</font>?


### Matrix operations

In [11]:
# The rest of the dicussion makes use of the following two square matrices

D = np.array( [ [1,2], [0, 0] ])
E = np.array( [ [0,0], [3,4] ])

print("D")
print(D)
print("E:")
print(E)

D
[[1 2]
 [0 0]]
E:
[[0 0]
 [3 4]]


In [ ]:
print("matrix sum:")
print(D+E)
print("matrix difference:")
print(D-E)
print("scalar mult:")
print(3*D)

In [ ]:
# what about this:

print(E*E)

**That's not matrix multiplication!!**  

Numpy has a special symbol for the <font color="red">**standard matrix multiplication**</font>:

In [ ]:
E@E

To compute <font color="red">**matrix powers**</font> we need to bring a function from a *subpackage* of numpy:

In [ ]:
from numpy.linalg import matrix_power as mpow

N = np.array([ [1, 1], [0, 1]])
print("N")
print(N)
print("2nd power")
print(mpow(N,2))
print("3rd power")
print(mpow(N,3))
print("4th power")
print(mpow(N,4))

# do you see a pattern? can you give a PROOF?
# can you give a GEOMETRIC EXPLANATION?

Last but not least:  <font color="red">**matrix inverse**</font> and
<font color="red">**determinant**</font>.
For that we need to bring in additional functions from the package **scipy.linalg** (already imported at the very top cell):

In [ ]:
D2 = np.array([[1,2],[3,4]])
print("inverse of D2:")
print(spla.inv(D2))

print("deteriminant of D")
spla.det(D)

It is easy to define your own function/subroutine.

In [ ]:
# user-defined function for doubling a matrix --- note that there is no restriction on
# the size of the input

def doublematrix(inputmatrix):
  return 2*inputmatrix

In [ ]:
# Let's test this function

A = np.array([[2,3,-4], [0,-6,7]])
print("A")
print(A)
print("apply function")
print(doublematrix(A))

**Numpy** and **scipy.linalg** has many more linear algebra functions.  We will introduce more as we go along.  But even these bits of python are enough to do *non-trivial linear algebra calculations*.

### Exercise (important:  you will need this for your group project!)

Write a python function
  &nbsp;
  &nbsp;
  &nbsp;
**swap(A, i, j)**
  &nbsp;
  &nbsp;
  &nbsp;
that swaps the i-th and j-th rows of the input matrix A.

